name: KAP Haber Takip

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 7-18 * * 1-5"

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Kutuphane kur
        run: pip install requests

      - name: KAP botu calistir
        run: python kap_takip.py
